var player,
    bunnyNPC,
    carrots,
    countCarrots = 0,
    neededCarrots,
    carrotsText,
    nest,
    dandelion,
    basil,
    ivy,
    lily,
    tulip,
    daisy,
    fox,
    platforms,
    cursors,
    keyQ,
    gameOver = false,
    health = 100,
    healthbar,
    healthText,
    homemenu,
    jumpVelocity = -330,
    vulnerableTime = 1000,
    camera,
    isPlayerMoving = false,
    speechBubble = false,
    speechBubbleText,
    speechbubbleShown,
    messageInfo,
    messageAlert,
    level2able = false;
    levelactive = 1;